package root.elements.network.modules.machine;

import java.util.ArrayList;
import java.util.Vector;

import logger.GlobalLogger;
import logger.XmlLogger;

import root.elements.network.modules.NetworkModule;
import root.elements.network.modules.link.Link;
import root.elements.network.modules.task.ISchedulable;
import root.elements.network.modules.task.MCMessage;
import root.elements.network.modules.task.NetworkMessage;
import root.util.constants.ConfigConstants;
import root.util.tools.NetworkAddress;

public class Machine extends NetworkModule {
	public NetworkAddress networkAddress;
	/* Indicates the total load for the node */
	public double nodeLoad;
	
	public Link[] portsOutput;
	public Link[] portsInput;
	
	/* Time for analysing a packet */
	public int analyseTime;
	/* Currently transmitted message */
	public ISchedulable currentlyTransmittedMsg;
	
	/* Contains all the messages generated by the machine */
	public ArrayList<ISchedulable> messageGenerator;
	
	public int ports_number;
	
	/* Buffering messages in an output buffer */
	public Vector<ISchedulable> outputBuffer;
	/* Buffering messages in an input buffer */
	public Vector<ISchedulable> inputBuffer;
	
	public String name; 
	
	/*XML LOG FILE*/
	public String logXML;
	public XmlLogger xmlLogger;
	
	
	public boolean needReload;
	
	public Machine(NetworkAddress addr_, String name_) throws Exception {
		super();
		name = name_;
		openPorts(ConfigConstants.CONST_PORT_NUMBER);
		networkAddress = addr_;
		outputBuffer = new Vector<ISchedulable>();
		inputBuffer  = new Vector<ISchedulable>();
		messageGenerator = new ArrayList<ISchedulable>();
		analyseTime = 0;
		needReload = true;
		nodeLoad = 0.0;
	}
	
	public Machine(NetworkAddress addr_) throws Exception {
		this(addr_, ""+addr_.value);
	}
	
	public void openPorts(int ports_) {
		portsOutput = new Link[ports_];
		portsInput  = new Link[ports_];
		ports_number = ports_;
	}
	
	public void setAddress(NetworkAddress networkAddress_) {
		/* Associate a networkAddress for current machine */
		this.networkAddress = networkAddress_;
	}
	
	public NetworkAddress getAddress() {
		return this.networkAddress;
	}
	
	public int connectOutput(Link link_) {
		/* Searching for next free port */
		int i = 0;
		while(portsOutput[i] != null){i++;}
		if(ports_number <= i) {
			GlobalLogger.warning("Can't connect machine : no free output port found");
			return 1;
		}
		
		portsOutput[i] = link_;
		
		return 0;
	}
	public int connectInput(Link link_) {
		/* Searching for next free port */
		int i = 0;
		while(portsInput[i] != null){i++;}
		if(ports_number <= i) {
			GlobalLogger.warning("Can't connect machine : no free input port found");
			return 1;
		}
		
		portsInput[i] = link_;
		
		return 0;
	}

	public int associateMessage(ISchedulable msg) {
		messageGenerator.add(msg);
		
		return 0;
	}
	
	public int sendMessage(ISchedulable msg) {
		GlobalLogger.debug("PUSHING "+msg.getName()+" MACHINE "+this.name);
		outputBuffer.add(msg);

		return 0;
	}
	
	public int generateMessage(int currentTime) {
		for(int i=0;i<messageGenerator.size();i++) {
			
			/* We get the message generator content. It includes all the messages
			 * which should be generated by a specified machine
			 */
			ISchedulable currentMsg = messageGenerator.get(i);
			ISchedulable newMsg = null;
			//GlobalLogger.debug("MSGGEN:"+currentMsg.getName()+"NS:"+currentMsg.getNextSend());
			
			if(currentMsg.getNextSend() == currentTime) {
				//GlobalLogger.debug("MSGGENOK:"+currentMsg.getName());
				try {
					//Make a copy for each periodic message
					if(ConfigConstants.MIXED_CRITICALITY) {
						newMsg = (((MCMessage) messageGenerator.get(i)).copy());
					}
					else {
						newMsg = (((NetworkMessage)messageGenerator.get(i)).copy());
					}
					
					newMsg.setCurrentNode(1);
					newMsg.setName(currentMsg.getName() + "_" + currentMsg.getNbExec());
					newMsg.setNextSend(currentTime);
					currentMsg.increaseNbExec();
					
					/* We put the copy in the input buffer of the generating node */
					inputBuffer.add(newMsg);
					if(currentMsg.getPeriod() != 0) {
						/* Periodic sending */
						currentMsg.setNextSend(currentMsg.getNextSend()+currentMsg.getPeriod());
					}
					else {
						/* Sporadic sending */
						messageGenerator.remove(i);
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}		
		}
		return 0;
	}
	
	
	
	/* Display infos functions */
	
	public int displayCurrentMessage() {
		if(currentlyTransmittedMsg != null) {
			GlobalLogger.log("MACHINE "+networkAddress.value+":CURRENTLY TREATING :"+currentlyTransmittedMsg.getName());			
		}
		else {
			GlobalLogger.log("MACHINE "+networkAddress.value+":NOTHING TO ANALYSE");
		}
		return 0;
	}
	
	public int displayOutputBuffer() {
		String message = "OuputBuffer de la machine "+networkAddress.value+"|";
		
		for(int cptMsgOutput = 0; cptMsgOutput < outputBuffer.size(); cptMsgOutput++) {
			ISchedulable currentMsg;
			if(ConfigConstants.MIXED_CRITICALITY) {
				 currentMsg = (MCMessage) outputBuffer.elementAt(cptMsgOutput);
			}
			else {
				 currentMsg = (NetworkMessage) outputBuffer.elementAt(cptMsgOutput);
			}
			
			message += currentMsg.getName();
		}
		message += "|";
		GlobalLogger.log(message);
		return 0;
	}
	
	public int displayInputBuffer() {
		ISchedulable currentMsg;
		String message = "InputBuffer de la machine "+networkAddress.value+"|";
		
		for(int cptMsgInput = 0; cptMsgInput < inputBuffer.size(); cptMsgInput++) {
			if(ConfigConstants.MIXED_CRITICALITY) {
				currentMsg = (MCMessage)inputBuffer.elementAt(cptMsgInput);
			}
			else {
				currentMsg = (NetworkMessage)inputBuffer.elementAt(cptMsgInput);
			}
			message += currentMsg.getName()+" ";
		}
		message += "|";
		GlobalLogger.log(message);
		return 0;
	}
	
	/* XML Writing functions */
	public int writeLogToFile(int timer) {
		if(currentlyTransmittedMsg != null) {
			xmlLogger.addChild("timer", xmlLogger.getRoot(), "value:"+timer,
					"message:"+currentlyTransmittedMsg.getName());		
		}
		else {
			xmlLogger.addChild("timer", xmlLogger.getRoot(), "value:"+timer+"");
		}
		return 0;
	}
	
	public int createXMLLog() {
		xmlLogger = new XmlLogger(this.name+".xml");
		xmlLogger.createDocument();
		xmlLogger.createRoot("machine");
		//xmlLogger.getRoot().setAttribute("id", this.networkAddress.value);
		xmlLogger.getRoot().setAttribute("name", this.name);
		return 0;
	}
}
